# Add patch, minor or major label to Pull Request depending on its notes
# Pull request notes must be in Keep a Changelog format
name: Update Pull Request labels

# trigger workflow if pull request was opened or edited
on:
  pull_request:
    types: [opened, edited]
  # remove manual dispatch if you do not need it
  workflow_dispatch:
    number:
      description: "Pull Request number"
      required: true

jobs:
  update-pull-request-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Get Pull Request
        uses: actions/github-script@v3
        id: pull-request
        with:
          script: |
            let pullRequest = null;
            if (context.payload.inputs && context.payload.inputs.number) {
              const number = context.payload.inputs.number;
              // find Pull Request by number fom input
              try {
                pullRequest = (await github.pulls.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: number,
                })).data;
              } catch(e) {
                core.error(`Cannot get Pull Request #${number}: ${e}`);
                return;
              }
            }
            if (context.payload.pull_request){
              // get Pull Request from event payload
              pullRequest = context.payload.pull_request;
            }

            if (!pullRequest) {
              core.error(`Cannot find Pull Request`);
              return;
            }

            core.setOutput('branch', pullRequest.head.ref);
            core.setOutput('number', pullRequest.number);
            core.setOutput('body', pullRequest.body);
            core.setOutput('labels', pullRequest.labels.map(data => data.name));
            return true;
      - name: Analyze PR notes
        id: notes
        if: "steps.pull-request.outputs.result"
        uses: vemel/nextchange@main
        with:
          # create release entry from pull request notes in output
          set: ${{ steps.pull-request.outputs.body }}
      - name: Update Pull Request labels
        uses: actions/github-script@v3
        if: "steps.pull-request.outputs.result"
        with:
          script: |
            // get suggested patch, minor or major label from pull request notes
            const number = ${{ steps.pull-request.outputs.number }};
            const branch = ${{ toJSON(steps.pull-request.outputs.branch) }};
            const label = ${{ toJSON(steps.notes.outputs.label) }};
            const oldLabels = ${{ steps.pull-request.outputs.labels }};

            // remove patch, minor and major label from pull request
            const managedLabels = ['patch', 'minor', 'major', 'release'];
            const otherLabels = oldLabels.filter(label => !managedLabels.includes(label));

            // add suggested label to Pull Request
            const newLabels = [...otherLabels, label];
            if (branch.startsWith('release/')) newLabels.push('release');
            core.info(`New labels: ${newLabels}`);

            await github.issues.setLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: number,
              labels: newLabels
            })
