# Update release draft on non-release pull request merge
name: Update Release draft from Pull Request notes

on:
  pull_request:
    types: [closed]
  # remove manual dispatch if you do not need it
  workflow_dispatch:
    number:
      description: "Pull Request number"
      required: true

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Get Pull Request
        uses: actions/github-script@v3
        id: pull-request
        with:
          script: |
            let pullRequest = null;
            if (context.payload.inputs && context.payload.inputs.number) {
              const number = context.payload.inputs.number;
              // find Pull Request by number fom input
              try {
                pullRequest = (await github.pulls.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: number,
                })).data;
              } catch(e) {
                core.error(`Cannot get Pull Request #${number}: ${e}`);
                return;
              }
            }
            if (context.payload.pull_request){
              // get Pull Request from event payload
              pullRequest = context.payload.pull_request;
            }

            if (!pullRequest) {
              core.error(`Cannot find Pull Request`);
              return;
            }

            // Stop if Pull request is not merged
            if (!pullRequest.merged) {
              core.info(`Pull Request ${pullRequest.number} is not merged, skipping Release draft update`);
              return;
            }

            // Stop if Pull Request branch name starts with `release`
            const branch = pullRequest.head.ref;
            if (branch.startsWith('release/')) {
              core.info(`This is a release branch ${branch}, skipping Release draft update`);
              return;
            }

            core.setOutput('branch', branch);
            core.setOutput('base', pullRequest.base.ref);
            core.setOutput('number', pullRequest.number);
            core.setOutput('url', pullRequest.html_url);
            core.setOutput('body', pullRequest.body);
            core.setOutput('suffix', `[#${pullRequest.number}](${pullRequest.html_url})`);
            return true;
      # Switch to Pull Request base branch to set release draft tag based on package.json and CHANGELOG.md
      - name: Checkout Pull Request base branch
        if: "steps.pull-request.outputs.result"
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.pull-request.outputs.base }}
      - name: Get Unreleased notes
        id: unreleased
        if: "steps.pull-request.outputs.result"
        uses: vemel/nextchange@main
        with:
          # get Unreleased section of CHANGELOG.md to set as a body of a newly created release draft
          get: Unreleased
          sanitize: true
      - name: Get or create Release draft
        uses: actions/github-script@v3
        id: release
        if: "steps.pull-request.outputs.result"
        with:
          script: |
            let release = null;
            const baseBranch = ${{ toJSON(steps.pull-request.outputs.base) }};

            // find existing relese draft for pull request base branch in first 100 releases
            const releasesResponse = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            for (let releaseItem of releasesResponse.data) {
              if (!releaseItem.draft) continue;
              if (releaseItem.target_commitish !== baseBranch) continue;
              release = releaseItem;
              core.info(`Found existing release draft ${release.name}`);
              break;
            }

            // create a release draft if there is none
            if (!release) {
              const response = await github.repos.createRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: '0.0.0',
                name: '0.0.0',
                draft: true,
                target_commitish: baseBranch,
                body: ${{ toJSON(steps.unreleased.outputs.result) }},
              })
              release = response.data;
              core.info(`Created Release draft ${release.name}`);
            }

            core.setOutput('id', release.id);
            core.setOutput("url", release.html_url);
            core.setOutput('tag', release.tag_name);
            core.setOutput('name', release.name);
            core.setOutput('body', release.body);
      - name: Build Release notes
        id: notes
        if: "steps.pull-request.outputs.result"
        uses: vemel/nextchange@main
        with:
          # add existing release notes as they are as notes
          set: ${{ steps.release.outputs.body }}
          # append pull request keep a changelog sections to notes
          append: ${{ steps.pull-request.outputs.body }}
          # add pull request link to each appended section
          suffix: ${{ steps.pull-request.outputs.suffix }}
      - name: Get suggested version
        id: version
        if: "steps.pull-request.outputs.result"
        uses: vemel/nextversion@main
        with:
          path: ./package.json
          # set release tag to a release candidate verion
          # you can change it to `stable`
          release: rc
          # bump version from package.json according to release notes
          result: ${{ steps.notes.outputs.label }}
      - name: Update release draft
        uses: actions/github-script@v3
        if: "steps.pull-request.outputs.result"
        with:
          script: |
            const releaseId = ${{ steps.release.outputs.id }};
            core.info(`Release ID: ${releaseId}`);

            // set release draft tag and name to suggested version
            const version = ${{ toJSON(steps.version.outputs.result) }};
            core.info(`Release version: ${version}`);

            // do not update release body if it already has link to this pull request
            const suffix = ${{ toJSON(steps.pull-request.outputs.suffix) }};
            const oldBody = ${{ toJSON(steps.release.outputs.body) }};
            const newBody = ${{ toJSON(steps.notes.outputs.result) }};
            const body = oldBody.includes(suffix) ? oldBody : newBody;
            core.info(`Release body: ${body}`);

            const response = await github.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: releaseId,
              tag_name: version,
              name: version,
              draft: true,
              body: body,
              prerelease: true,
            });
            core.info(`Release URL: ${response.data.html_url}`);
      - name: Add comment to Pull Request
        uses: actions/github-script@v3
        if: "steps.pull-request.outputs.result"
        with:
          script: |
            const issueNumber = ${{ steps.pull-request.outputs.number }};
            const version = ${{ toJSON(steps.version.outputs.result) }};
            const response = await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: `Pull request notes were merged to release draft ${version}`,
            });
            core.info(`Comment URL: ${response.data.html_url}`);
